### ISSUE TITLE
Pixie Dust doesn't run properly

### ISSUE THREAD

**Issue by zohaibcheema** [anbuinfosec/wipwn#7]
I having issues while using Wipwn in Termux (ROOT) sometimes it's work perfectly and sometimes it's doesn't work on same router. I've tested twice on Same router in the first attempt it's work great and when i tried second time it's show me a error that Pixie Dust Data isn't enough to run.
Please let me know how i can fixt this error

**Comment by anbuinfosec** [comment]
It depends on wifi router vulnerability.
