### ISSUE TITLE
It didn't work 

### ISSUE THREAD

**Issue by selenium2106** [anbuinfosec/wipwn#8]
I have tried this script on several of my rooted devices, but this time it did not work on a moto g5 plus, for some reason the console shows me this error: 
Cannot find device "wlan0"
Unable to up interface "wlan0".
I have already tried different solutions, from turning off the WiFi, to restarting the phone, but nothing, the program works halfway when it starts with WiFi on:
 [*] Running wpa_supplicant…
[*] Trying PIN '12345670'…
[*] Scanning…
[*] Associating with AP…
[+] Associated with 40:3F:8C:9D:9B:72 (ESSID: UNE_74B5 AP)
[*] Scanning…
[*] Associating with AP…
[+] Associated with 40:3F:8C:9D:9B:72 (ESSID: UNE_74B5 AP)
[*] Scanning…
[*] Associating with AP…
[+] Associated with 40:3F:8C:9D:9B:72 (ESSID: UNE_74B5 AP)
[*] Scanning…
^C
Aborting…
It just stays in that loop until you stop it. The truth is I don't know what else to do, I did everything possible to try to solve it, but to no avail. If anyone has had the same thing happen to them and solved this problem, please enlighten with your answer, if this has no solution, I will take it as a hardware incompatibility.

**Comment by anbuinfosec** [comment]
The error message "Cannot find device 'wlan0'" indicates that the script is looking for a wireless interface named 'wlan0', but it's unable to find it on your Moto G5 Plus.
