### ISSUE TITLE
Stuck/not working ..

### ISSUE THREAD

**Issue by mkr-infinity** [anbuinfosec/wipwn#9]
I have SM-J8810G rooted i am using latest termux from github ,
I have disabled wifi
Enabled hotspot , and location 
Whenever i run bash wipwn.sh sometimes it gives me error. 
Sometimes without error works but stuck on trying pin.. more than 10 minutes. How to fix it.
![Screenshot_20240610-090608_Termux](https://github.com/anbuinfosec/wipwn/assets/125804924/93de5c33-689d-4631-ac3c-b7f45b494008)

Sometimes got this error 👇
![Screenshot_20240610-091237_Termux](https://github.com/anbuinfosec/wipwn/assets/125804924/f6ca7cdd-5065-40bc-84b5-3f177f34ede5)

**Comment by anbuinfosec** [comment]
This is an encoding error. Update all your modules and packages. Hope it gets fixed.

**Comment by mkr-infinity** [comment]
> This is an encoding error. Update all your modules and packages. Hope it gets fixed.

Still same error bro

**Comment by Gilbert020994** [comment]
Same error too
